# Generated by Django 3.1.2 on 2020-11-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201109_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
