# Generated by Django 3.1.2 on 2020-11-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(to='home.Questions'),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='exam',
        ),
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ManyToManyField(to='home.Exam'),
        ),
    ]
