# Generated by Django 3.1.2 on 2020-11-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201126_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(to='home.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='exam',
            field=models.ManyToManyField(to='home.Exam'),
        ),
    ]
