# Generated by Django 3.1.2 on 2020-12-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201207_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='a',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='home.Subjects'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(to='home.Exam'),
        ),
    ]
