# Generated by Django 3.1.2 on 2020-12-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201207_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='home.Subjects'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(to='home.Exam'),
        ),
    ]
